reminder:
    username: shiqianfeng
    password: lwh901201
    telPhone: 17767264190

# 短信服务配置
sms:
  props:
    accessKey: LTAIaToV0a0KJjfA # 不能外泄, 请注意保密!
    accessSecret: 3jGpRZHmK1N4CrR52ojzosxTIK8SJQ  # 不能外泄, 请注意保密!
    regionId: cn-hangzhou
    endpointName: cn-hangzhou
    signName: 小宝科技
    templateCode: SMS_96815008